on:
  schedule:
    - cron: "0 0 * * 0" # rebuild once a week
  release:
  push:
    tags:
      - "*"
    branches:
      - "build"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{ toJSON(github.event) }}"
